name = "The Grumbles"
description = "Music, sadness, silliness"
keywords = "indie, punk, millenial, anime, alternative, indie rock, nerd rock, Colorado Springs, Colorado, Southern Colorado"
image = "mascotblurred small square.jpg"
theme = "dark"
primary_color = "#e08a12"
text_align = "center"
gtag_id = ""
base_url = "https://samriggio.github.io/realgrumbles"

[[sections]]
title = "Music"
description = ""
direction = "column"
item_style = "outline"
[[sections.items]]
title = "A Pretty Bad Good EP"
description = "Download our first release FREE"
embed_url = "https://download-directory.github.io?url=https://github.com/samriggio/realgrumbles/tree/main/dist/music/A%20Pretty%20Bad%20Good&filename=The%20Grumbles%20-%20A%20Pretty%20Bad%20Good"

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://instagram.com/realgrumbles"
[[sections.items]]
icon = "https://cdn.simpleicons.org/bandcamp/ffffff"
title = "Bandcamp"
url = "https://thegrumbles.bandcamp.com"

